#pragma once

#include <memory>
#include "../blockentity/BlockEntity.h"
#include "../util/Brightness.h"
#include "LightLayer.h"
#include "DimensionId.h"

//class MaterialType;
class Level;
class ChunkSource;
class BlockPos;
class BlockID;
class BlockTickingQueue;
class LevelChunk;
class FullBlock;
class HitResult;
class Vec3;
class AABB;
class Material;
class BlockEntity;
class LightLayer;
class ChunkPos;
class Bounds;
class TileTickingQueue;
class Dimension;
class BlockSourceListener;
class Biome;
// Size : 76
class BlockSource
{
public:
	BlockSource(Level &, Dimension &, ChunkSource &, bool, bool);
	virtual ~BlockSource();
	void _fireColumnDirty(int, int, int, int, int);
	void _getSkyDarken();
	void _isIceAt(BlockPos const &);
	void _isWaterAt(BlockPos const &);
	void _neighborChanged(BlockPos const &, BlockPos const &, BlockID);
	void _tileChanged(BlockPos const &, FullBlock, FullBlock, int);
	void addListener(BlockSourceListener &);
	void blockEvent(BlockPos const &, int, int);
	void blockEvent(int, int, int, int, int);
	void canSeeSky(BlockPos const &);
	void canSeeSky(int, int, int);
	void checkIsTopRainBlockPos(BlockPos const &);
	void clearCachedLastChunk();
	void clip(Vec3 const &, Vec3 const &, bool, bool, int);
	void containsAny(BlockPos const &, BlockPos const &);
	void containsAnyLiquid(AABB const &);
	void containsFireBlock(AABB const &);
	//void containsLiquid(AABB const &, MaterialType);
	//void containsMaterial(AABB const &, MaterialType);
	void fetchAABBs(AABB const &, bool);
	void findNextTopSolidBlockUnder(BlockPos &);
	void fireAreaChanged(BlockPos const &, BlockPos const &);
	void fireBlockChanged(BlockPos const &, FullBlock, FullBlock, int);
	void fireBlockEntityChanged(BlockEntity &);
	void fireBlockEntityRemoved(std::unique_ptr<BlockEntity>);
	void fireBlockEvent(int, int, int, int, int);
	void fireBlocksDirty(int, int, int, int, int, int);
	void fireBrightnessChanged(BlockPos const &);
	Biome* getBiome(BlockPos const &);
	Block* getBlock(BlockPos const &);
	Block* getBlock(int, int, int);
	FullBlock getBlockAndData(BlockPos const &);
	FullBlock getBlockAndData(int, int, int);
	BlockEntity* getBlockEntity(BlockPos const &);
	BlockEntity* getBlockEntity(int, int, int);
	BlockID getBlockID(BlockPos const &);
	BlockID getBlockID(int, int, int);
	Brightness getBrightness(BlockPos const &);
	Brightness getBrightness(LightLayer const &, BlockPos const &);
	Brightness getBrightness(LightLayer const &, int, int, int);
	Brightness getBrightness(int, int, int);
	LevelChunk* getChunk(ChunkPos const &);
	LevelChunk* getChunk(int, int);
	LevelChunk* getChunkAt(BlockPos const &);
	LevelChunk* getChunkAt(int, int, int);
	ChunkSource* getChunkSource();
	int getData(BlockPos const &);
	int getData(int, int, int);
	Dimension* getDimension();
	Dimension const*const getDimensionConst();
	DimensionId getDimensionId()const;
	//void getEntities(EntityType, AABB const &, Entity *);
	int getExtraData(BlockPos const &);
	int getGrassColor(BlockPos const &);
	void getHeightmap(BlockPos const &);
	void getHeightmap(int, int);
	void getHeightmapPos(BlockPos const &);
	Level& getLevel();
	Level const& getLevelConst();
	void getLightColor(BlockPos const &, int);
	void getMaterial(BlockPos const &);
	void getMaterial(int, int, int);
	/*void getMobsAt(EntityType, BlockPos const &);
	void getNearestEntityNotOfType(Entity *, Vec3 const &, float, EntityType);
	void getNearestEntityOfType(Entity *, AABB const &, EntityType);
	void getNearestEntityOfType(Entity *, Vec3 const &, float, EntityType);
	*/void getPublicSource();
	void getRawBrightness(BlockPos const &, bool);
	void getRawBrightness(int, int, int, bool);
	void getSeenPercent(Vec3 const &, AABB const &);
	void getTickQueue(BlockPos const &);
	void getTopBlock(int, int &, int);
	void getTopRainBlockPos(BlockPos const &);
	void getTopSolidBlock(BlockPos const &, bool);
	void getTopSolidBlock(int, int, bool);
	void getWritableChunk(ChunkPos const &);
	bool hasBlock(BlockPos const &);
	bool hasBlock(int, int, int);
	void hasChunksAt(AABB const &);
	void hasChunksAt(BlockPos const &, BlockPos const &);
	void hasChunksAt(BlockPos const &, int);
	void hasChunksAt(Bounds const &);
	void hasChunksAt(int, int, int, int);
	void isConsideredSolidBlock(BlockPos const &);
	void isConsideredSolidBlock(int, int, int);
	void isEmptyBlock(BlockPos const &);
	void isEmptyBlock(int, int, int);
	void isHumidAt(BlockPos const &);
	void isOwnerThread();
	//void isPositionUnderLiquid(BlockPos const &, MaterialType);
	void isSnowTemperature(BlockPos const &);
	void isSolidBlockingBlock(BlockPos const &);
	void isSolidBlockingBlock(int, int, int);
	void isTopSolidBlocking(Block *, unsigned char);
	void isTopSolidBlocking(BlockPos const &);
	void isTopSolidBlocking(int, int, int);
	void onChunkDiscarded(LevelChunk &);
	void removeBlock(BlockPos const &);
	void removeBlock(int, int, int);
	void removeListener(BlockSourceListener &);
	void runLightUpdates(LightLayer const &, BlockPos const &, BlockPos const &);
	void setBlock(BlockPos const &, BlockID, int);
	void setBlock(int, int, int, BlockID, int);
	void setBlockAndData(BlockPos const &, BlockID, unsigned char, int);
	void setBlockAndData(BlockPos const &, FullBlock, int);
	void setBlockAndData(int, int, int, BlockID, unsigned char, int);
	void setBlockAndData(int, int, int, FullBlock, int);
	void setBlockAndDataNoUpdate(int, int, int, FullBlock);
	void setBlockNoUpdate(int, int, int, BlockID);
	void setBrightness(LightLayer const &, BlockPos const &, Brightness);
	void setBrightness(LightLayer const &, int, int, int, Brightness);
	void setExtraData(BlockPos const &, unsigned short);
	void setGrassColor(int, BlockPos const &, int);
	void setTickingQueue(BlockTickingQueue &);
	void shouldFireEvents(LevelChunk &);
	void shouldFreeze(BlockPos const &, bool);
	void shouldThaw(BlockPos const &, bool);
	void updateLightIfOtherThan(LightLayer const &, BlockPos const &, Brightness);
	void updateNeighborsAt(BlockPos const &);
	void shouldFreezeIgnoreNeighbors(BlockPos const&);
};
