#pragma once

#include "mcpe/item/Item.h"

class TextureUVCoordinateSet;

namespace IC
{
class Items : public Item
{
public:
	class ID
	{
	public:
		static const short mPainter=501;
		static const short mRubber=502;
		static const short mTreeTap=503;
		static const short mResin=504;
		static const short mICCoin=505;
		static const short mSlag=510;
		static const short mScrap=511;
		static const short mForgeHammer=512;
		static const short mElectricTreeTap=513;
		static const short mCoil=515;
		static const short mPowerUnitSmall=516;
		static const short mElectricMotor=517;
		static const short mElectricHoe=518;
		static const short mChainsaw=519;
		static const short mSingleUseBattery=520;
		static const short mTinIngot=522;
		static const short mSteelIngot=523;
		static const short mCopperIngot=524;
		static const short mLeadIngot=525;
		static const short mBronzeIngot=526;
		static const short mAlloyIngot=527;
		static const short mCircuit=528;
		static const short mAdvancedCircuit=529;
		static const short mBronzePlate=530;
		static const short mCopperPlate=531;
		static const short mGoldPlate=532;
		static const short mIronPlate=533;
		static const short mLapisPlate=534;
		static const short mLeadPlate=535;
		static const short mObsidianPlate=536;
		static const short mSteelPlate=537;
		static const short mTinPlate=538;
		static const short mDenseBronzePlate=539;
		static const short mDenseCopperPlate=540;
		static const short mDenseGoldPlate=541;
		static const short mDenseIronPlate=542;
		static const short mDenseLapisPlate=543;
		static const short mDenseLeadPlate=544;
		static const short mDenseObsidianPlate=545;
		static const short mDenseSteelPlate=546;
		static const short mDenseTinPlate=547;
		static const short mBronzeDust=548;
		static const short mClayDust=549;
		static const short mCoalDust=550;
		static const short mCoalFuelDust=551;
		static const short mCopperDust=552;
		static const short mDiamondDust=553;
		static const short mEnergiumDust=554;
		static const short mGoldDust=555;
		static const short mIronDust=556;
		static const short mLapisDust=557;
		static const short mLeadDust=558;
		static const short mLithiumDust=559;
		static const short mObsidianDust=560;
		static const short mSiliconDioxideDust=561;
		static const short mSilverDust=562;
		static const short mStoneDust=563;
		static const short mSulfurDust=564;
		static const short mTinDust=565;
		static const short mSmallBronzeDust=567;
		static const short mSmallCopperDust=568;
		static const short mSmallGoldDust=569;
		static const short mSmallIronDust=570;
		static const short mSmallLapisDust=571;
		static const short mSmallLeadDust=572;
		static const short mSmallObsidianDust=573;
		static const short mSmallLithiumDust=574;
		static const short mSmallSilverDust=575;
		static const short mSmallSulfurDust=576;
		static const short mSmallTinDust=577;
		static const short mBlankTFBP=578;
		static const short mChillingTFBP=579;
		static const short mCultivationTFBP=580;
		static const short mDesertificationTFBP=581;
		static const short mFlatificationTFBP=582;
		static const short mIrrigationTFBP=583;
		static const short mMushroomTFBP=584;
		static const short mCrushedCopper=585;
		static const short mCrushedGold=586;
		static const short mCrushedIron=587;
		static const short mCrushedLead=588;
		static const short mCrushedSilver=589;
		static const short mCrushedTin=590;
		static const short mCrushedUranium=591;
		static const short mPurifiedCopper=592;
		static const short mPurifiedGold=593;
		static const short mPurifiedIron=594;
		static const short mPurifiedLead=595;
		static const short mPurifiedSilver=596;
		static const short mPurifiedTin=597;
		static const short mPurifiedUranium=598;
		static const short mCasingBronze=599;
		static const short mCasingCopper=600;
		static const short mCasingGold=601;
		static const short mCasingIron=602;
		static const short mCasingLead=603;
		static const short mCasingSteel=604;
		static const short mCasingTin=605;
		static const short mPainterBlack=606;
		static const short mPainterRed=607;
		static const short mPainterBrown=608;
		static const short mPainterGreen=609;
		static const short mPainterBlue=610;
		static const short mPainterPurple=611;
		static const short mPainterCyan=612;
		static const short mPainterGray=613;
		static const short mPainterLightGray=614;
		static const short mPainterPink=615;
		static const short mPainterLime=616;
		static const short mPainterYellow=617;
		static const short mPainterLightBlue=618;
		static const short mPainterMagenta=619;
		static const short mPainterOrange=620;
		static const short mPainterWhite=621;
		static const short mTinCable0=622;
		static const short mTinCable1=623;
		static const short mIronCable0=624;
		static const short mIronCable1=625;
		static const short mIronCable2=626;
		static const short mIronCable3=627;
		static const short mGoldCable0=628;
		static const short mGoldCable1=629;
		static const short mGoldCable2=630;
		static const short mCopperCable0=631;
		static const short mCopperCable1=632;
		static const short mDetectorCable=633;
		static const short mGlassCable=634;
		static const short mSplitterCable=635;
		static const short mBronzeShovel=636;
		static const short mBronzeHoe=637;
		static const short mBronzePickAxe=638;
		static const short mBronzeAxe=639;
		static const short mBronzeSword=640;
		static const short mEjector=641;
		static const short mEjectorUp=642;
		static const short mEjectorDown=643;
		static const short mEjectorWest=644;
		static const short mEjectorEast=645;
		static const short mEjectorSouth=646;
		static const short mEjectorNorth=647;
		static const short mFluidEjector=648;
		static const short mFluidEjectorUp=649;
		static const short mFluidEjectorDown=650;
		static const short mFluidEjectorWest=651;
		static const short mFluidEjectorEast=652;
		static const short mFluidEjectorSouth=653;
		static const short mFluidEjectorNorth=654;
		static const short mFluidPulling=655;
		static const short mFluidPullingUp=656;
		static const short mFluidPullingDown=657;
		static const short mFluidPullingWest=658;
		static const short mFluidPullingEast=659;
		static const short mFluidPullingSouth=660;
		static const short mFluidPullingNorth=661;
		static const short mPulling=662;
		static const short mPullingUp=663;
		static const short mPullingDown=664;
		static const short mPullingWest=665;
		static const short mPullingEast=666;
		static const short mPullingSouth=667;
		static const short mPullingNorth=668;
		static const short mTransformer=669;
		static const short mRedstoneInverter=670;
		static const short mOverclocker=671;
		static const short mEnergyStorage=672;
		static const short mIronRotorBlade=673;
		static const short mIronRotor=674;
		static const short mIronShaft=675;
		static const short mIridiumOre=673;
		static const short mIridiumShard=674;
		static const short mIridiumPlate=675;
		static const short mSteelRotorBlade=673;
		static const short mSteelRotor=674;
		static const short mSteelShaft=675;
		static const short mSteelBlockCuttingBlade=676;
		static const short mIronBlockCuttingBlade=677;
		static const short mDiamondBlockCuttingBlade=678;
		static const short mWoodRotorBlade=679;
		static const short mWoodRotor=680;
		static const short mAshes=681;
		static const short mAlloyPlate=682;
		static const short mCarbonFibre=683;
		static const short mCarbonMesh=684;
		static const short mCarbonPlate=685;
		static const short mCarbonRotorBlade=686;
		static const short mCarbonRotor=687;
		static const short mCoalBall=688;
		static const short mCoalBlock=689;
		static const short mCoalChunk=690;
	};
public:
	static void initICAllItems();
	static void addICCreativeItems();
private:
	static void initICItems();
	static void initICBlockItems();
public:
	static bool mICItems[4096];
public:
	Items(std::string const&,short);
public:
	virtual bool isBatteryItem()const;
	virtual unsigned int getEU(ItemInstance const&)const;
	virtual unsigned int getMaxEU()const;
public:
	static void registerItem(short,std::string const&,std::string const&,int);
	static void registerItem(short,std::string const&,TextureUVCoordinateSet const&);
};
}
